[project]
name = "mcp-demo"
version = "0.0.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.4",
    "beautifulsoup4>=4.13.4",
    "mcp[cli]>=1.9.1",
    "bs4>=0.0.2",
]
